import { ColorSchemeConfig, AppSettings } from "../types";

export const defaultColorSchemes: ColorSchemeConfig[] = [
  {
    id: "aurora",
    name: "Aurora",
    colors: {
      bg: "#020617",
      fg: "#f8fafc",
      black: "#0f172a",
      red: "#ef4444",
      green: "#10b981",
      yellow: "#f59e0b",
      blue: "#3b82f6",
      purple: "#8b5cf6",
      cyan: "#06b6d4",
      white: "#f8fafc",
    },
  },
  {
    id: "campbell",
    name: "Campbell",
    colors: {
      bg: "#0C0C0C",
      fg: "#CCCCCC",
      black: "#0C0C0C",
      red: "#C50F1F",
      green: "#13A10E",
      yellow: "#C19C00",
      blue: "#0037DA",
      purple: "#881798",
      cyan: "#3A96DD",
      white: "#CCCCCC",
    },
  },
  {
    id: "oneHalfDark",
    name: "One Half Dark",
    colors: {
      bg: "#282C34",
      fg: "#DCDFE4",
      black: "#282C34",
      red: "#E06C75",
      green: "#98C379",
      yellow: "#E5C07B",
      blue: "#61AFEF",
      purple: "#C678DD",
      cyan: "#56B6C2",
      white: "#DCDFE4",
    },
  },
  {
    id: "solarizedDark",
    name: "Solarized Dark",
    colors: {
      bg: "#002B36",
      fg: "#839496",
      black: "#073642",
      red: "#DC322F",
      green: "#859900",
      yellow: "#B58900",
      blue: "#268BD2",
      purple: "#D33682",
      cyan: "#2AA198",
      white: "#EEE8D5",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    colors: {
      bg: "#282A36",
      fg: "#F8F8F2",
      black: "#21222C",
      red: "#FF5555",
      green: "#50FA7B",
      yellow: "#F1FA8C",
      blue: "#BD93F9",
      purple: "#FF79C6",
      cyan: "#8BE9FD",
      white: "#F8F8F2",
    },
  },
  {
    id: "githubDark",
    name: "GitHub Dark",
    colors: {
      bg: "#0D1117",
      fg: "#B3B1AD",
      black: "#484F58",
      red: "#FF7B72",
      green: "#3FB950",
      yellow: "#D29922",
      blue: "#58A6FF",
      purple: "#BC8CFF",
      cyan: "#39C5CF",
      white: "#B1BAC4",
    },
  },
];

export const defaultSettings: AppSettings = {
  language: "en",
  fontFamily: "JetBrains Mono",
  fontSize: 14,
  lineHeight: 1.2,
  glassmorphism: true,
  glassOpacity: 0.4,
  glassBlur: 12,
  defaultBaudRate: 115200,
  colorScheme: "aurora",
  customColorSchemes: [],
  showAurora: true,
  auroraSpeed: 1.0,
  backgroundImage: null,
  cursorShape: "bar",
  cursorBlink: true,
  scrollbackLines: 1000,
  copyOnSelect: true,
  pasteOnRightClick: true,
  pluginPath: "",
  showTimestamp: true,
};
